"""
Merge editorial content into team_reviews.json and generate website data files.

Reads:
  data/raw/content/content_dump.json              — team editorial content (31 spotlight teams)
  data/raw/content/content_non_spotlight_teams.json — editorial content for non-spotlight teams
  data/raw/content/group_review.json              — group editorial content (12 groups)

Writes:
  output/export/team_reviews.json     — updated with editorial fields
  output/export/groups.json           — group editorial data
  website/data/teams.js               — JS module for browser
  website/data/groups.js              — JS module for browser

Both source files may contain multiple concatenated JSON arrays (from ChatGPT batch
copying). The parser handles this automatically.
"""
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

SCRAPER               = Path(__file__).parent
CONTENT_FILE          = SCRAPER / "data/raw/content/content_dump.json"
NON_SPOTLIGHT_FILE    = SCRAPER / "data/raw/content/content_non_spotlight_teams.json"
GROUPS_FILE           = SCRAPER / "data/raw/content/group_review.json"
EXPORT                = SCRAPER / "output/export"
WEBSITE               = SCRAPER.parent / "website/data"

# Fields to copy from content_dump entries into team_reviews (spotlight teams)
TEAM_FIELDS = [
    "story",
    "defense",
    "midfield",
    "attack",
    "fun_fact",
    "key_players",
    "goalkeeper_note",
    "recent_world_cup_history",
]

# Fields to copy from non-spotlight content
NON_SPOTLIGHT_FIELDS = [
    "playstyle",
    "history",
    "heartbreak_angle",
    "fun_fact",
    "players_to_watch",
]


def parse_multi_array(path: Path) -> list:
    """Parse a file that may contain multiple concatenated JSON arrays.
    Also normalises curly/smart quotes to straight ASCII quotes."""
    text = path.read_text(encoding="utf-8").strip()
    # Normalise typographic quotes to plain ASCII double/single quotes
    text = text.replace('“', '"').replace('”', '"')
    text = text.replace('‘', "'").replace('’', "'")
    items = []
    decoder = json.JSONDecoder()
    pos = 0
    while pos < len(text):
        # Skip whitespace between arrays
        while pos < len(text) and text[pos] in " \t\r\n":
            pos += 1
        if pos >= len(text):
            break
        obj, end = decoder.raw_decode(text, pos)
        if isinstance(obj, list):
            items.extend(obj)
        else:
            items.append(obj)
        pos = end
    return items


def main():
    EXPORT.mkdir(parents=True, exist_ok=True)
    WEBSITE.mkdir(parents=True, exist_ok=True)

    # ── Load editorial content ────────────────────────────────────────────────
    team_content       = {t["country"]: t for t in parse_multi_array(CONTENT_FILE)}
    non_spotlight_content = {t["country"]: t for t in parse_multi_array(NON_SPOTLIGHT_FILE)}
    group_content      = {g["group"]:   g for g in parse_multi_array(GROUPS_FILE)}
    print(f"Loaded {len(team_content)} spotlight team entries    from {CONTENT_FILE.name}")
    print(f"Loaded {len(non_spotlight_content)} non-spotlight entries from {NON_SPOTLIGHT_FILE.name}")
    print(f"Loaded {len(group_content)} group entries              from {GROUPS_FILE.name}")

    # ── Merge team content into team_reviews.json ─────────────────────────────
    tr_path = EXPORT / "team_reviews.json"
    teams   = json.loads(tr_path.read_text(encoding="utf-8"))

    merged     = 0
    ns_merged  = 0
    skipped    = []
    for team in teams:
        country = team["country"]
        if country in team_content:
            c = team_content[country]
            for field in TEAM_FIELDS:
                if field in c:
                    team[field] = c[field]
            merged += 1
        elif country in non_spotlight_content:
            c = non_spotlight_content[country]
            # Map "intro" → "story" so the same template field works
            if c.get("intro"):
                team["story"] = c["intro"]
            for field in NON_SPOTLIGHT_FIELDS:
                if field in c:
                    team[field] = c[field]
            ns_merged += 1
        else:
            if team.get("spotlight"):
                skipped.append(country)

    tr_path.write_text(json.dumps(teams, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\nTeam reviews: {merged} spotlight + {ns_merged} non-spotlight updated, {len(skipped)} spotlight missing")
    if skipped:
        for s in skipped:
            print(f"  MISSING: {s}")

    # ── Regenerate teams.js ───────────────────────────────────────────────────
    js_body = json.dumps(teams, ensure_ascii=False, indent=2)
    (WEBSITE / "teams.js").write_text(
        f"// Auto-generated by merge_content.py — do not edit manually\n"
        f"export const TEAMS = {js_body};\n",
        encoding="utf-8",
    )
    print(f"Wrote {WEBSITE / 'teams.js'}")

    # ── Write groups.json + groups.js ─────────────────────────────────────────
    groups_list = sorted(group_content.values(), key=lambda g: g["group"])

    groups_json_path = EXPORT / "groups.json"
    groups_json_path.write_text(
        json.dumps(groups_list, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"Wrote {groups_json_path} ({len(groups_list)} groups)")

    groups_js_body = json.dumps(groups_list, ensure_ascii=False, indent=2)
    (WEBSITE / "groups.js").write_text(
        f"// Auto-generated by merge_content.py — do not edit manually\n"
        f"export const GROUPS = {groups_js_body};\n",
        encoding="utf-8",
    )
    print(f"Wrote {WEBSITE / 'groups.js'}")

    # ── Summary ───────────────────────────────────────────────────────────────
    with_story   = sum(1 for t in teams if t.get("story"))
    with_kp      = sum(1 for t in teams if t.get("key_players"))
    with_defense = sum(1 for t in teams if t.get("defense"))
    print(f"\n━━ MERGE COMPLETE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print(f"Teams with story:        {with_story}/48")
    print(f"Teams with key_players:  {with_kp}/48")
    print(f"Teams with defense/mid/attack: {with_defense}/48")
    print(f"Groups with full review: {len(groups_list)}/12")


if __name__ == "__main__":
    main()
